# Configure Wi-Fi and MQTT broker settings
SSID = "SSID"
PASSWORD = "PASSWORD"
MQTT_BROKER = "XXX.XXX.XXX.XXX"
MQTT_PORT = XXX
MQTT_USER = "MQTT USER"
MQTT_PASSWORD = "MQTT PASSWORD"
MQTT_TOPIC = "homeassistant/device/sensor"
CLIENT_ID = "CLIENT ID"
MQTT_KEEPALIVE = 60
